# _config.yml

title: Hichem Ben Marzoug
tagline: IT Management Professional | System Mergers & Operational Strategy
description: >-
  The professional portfolio and blog of Hichem Ben Marzoug, an IT leadership
  professional specializing in system mergers, cloud infrastructure, and operational efficiency.

# URL and Baseurl
baseurl: ""
url: "https://hichem.tech"

# Build settings
enable_retina: false
permalink: :title

# Navigation
nav_list:
  Home: ['Home', '/', 'fa-home']
  About: ['About', '/about/', 'fa-user']
  Projects: ['Projects', '/projects/', 'fa-briefcase']
  Blog: ['Blog', '/blog/', 'fa-pencil']
  Contact: ['Contact', '/contact/', 'fa-envelope']

# Footer Links (for the mini-footer on some pages)
single_footer: '<p>Hichem BM 2025 | <a href="/blog">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Contact: ['Contact', '/contact/']
    LinkedIn: ['LinkedIn', 'https://www.linkedin.com/in/hichem-bm/', 'fa-linkedin']


# Build settings
# markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
