# Site settings
title: Hichem BM | IT Lead in the Paris area
email: # You can add your email here later if you wish
description: >
  Senior IT Manager with over a decade of experience helping startups and scale-ups build their IT department.
baseurl: "" # For a user site, this should be empty
url: "https://hichembm.github.io" # IMPORTANT: Set this to your live URL
enable_retina: false
permalink: :title

# Navigation
nav_list:
  Home: ['Home', '/', 'fa-home']
  About: ['About', '/about/', 'fa-user']
  Projects: ['Projects', '/projects/', 'fa-briefcase']
  Blog: ['Blog', '/blog/', 'fa-pencil']
  Contact: ['Contact', '/contact/', 'fa-envelope']

# Footer for static pages (like About, 404). Note the ' for Let's is escaped with a second '.
single_footer: '<p>Hichem BM&copy; | Let''s Discuss Your Next Challenge -> <a href="https://www.linkedin.com/in/hichem-bm/">Connect with me</a></p>'

# Footer for pages with sidebars (like Home, Blog, Projects)
footer_links:
  About: ['About', '/about/']
  Contact: ['Contact', '/contact/', 'fa-envelope']
  LinkedIn: ['LinkedIn', 'https://www.linkedin.com/in/hichem-bm/', 'fa-linkedin']
